version: '2'
services:
    firstjh-app:
        image: firstjh
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://firstjh-mariadb:3306/firstjh
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://firstjh-elasticsearch:9200
        ports:
            - 8080:8080
    firstjh-mariadb:
        extends:
            file: mariadb.yml
            service: firstjh-mariadb
    firstjh-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: firstjh-elasticsearch
